Created basic structure
serhii-shyian/bookstore-app pull request #1
Opened 2024-05-25 13:49 UTC by serhii-shyian

1) Add checkstyle.xml in the root, pointed in pom.xml and build part
2) Add dependencies in pom.xml
3) Add application.properties in resources package
4) Add init_db.sql in resources package
5) Add application.properties in test/resources package
6) Add Book class in model package
7) Add DataProcessingException in exception package
8) Add BookRepository in repository package and BookRepositoryImpl in repository/impl package
9) Add BookService in service package and BookServiceImpl in service/impl package

2024-05-25 13:54 UTC, okuzan requested changes

2024-05-25 13:54 UTC, okuzan commented on src/main/java/com/example/bookstore/model/Book.java
> +    private String title;
use @ column nullable = false

2024-05-28 05:08 UTC, Elena-Bruyako requested changes
Provide Main class with implementation according to the task: Class with @SpringBootApplication annotation that will have a CommandLineRunner bean.

2024-05-28 05:08 UTC, Elena-Bruyako commented on src/main/java/com/example/bookstore/model/Book.java
> +@Data
Don't use `@Data` for entities, find article about it

2024-05-28 05:08 UTC, Elena-Bruyako commented on src/main/java/com/example/bookstore/model/Book.java
> +    public Book() {
You don't need to create default constructor for entity if you don't have any with parameters

2024-05-29 05:11 UTC, Elena-Bruyako requested changes
Let's make it perfect!

2024-05-29 05:11 UTC, Elena-Bruyako commented on src/main/java/com/example/bookstore/model/Book.java
> +@NoArgsConstructor
In Java constructor without parameters is created by default when you create an object: Book book = new Book(); 
If you have at least one constructor with parameters, you must create default constructor by yourself for Entity.

2024-05-29 05:11 UTC, Elena-Bruyako commented on src/main/java/com/example/bookstore/model/Book.java
> +@NoArgsConstructor
```suggestion
```

2024-05-29 05:11 UTC, Elena-Bruyako commented on src/main/java/com/example/bookstore/model/Book.java
> +    @Column(name = "cover_image")
Hibernate autogenerate the name using snake_case
```suggestion
```

2024-05-29 12:13 UTC, Elena-Bruyako approved these changes
Well done!

2024-05-30 04:09 UTC, merged